version: '3'
services:

  goodcache:
    image: redis
    ports:
      - 6379:6379
  ing-test:
    image: thealmikey/apichallenge:0.0.4
    ports:
      - 8080:8080
    depends_on:
      - goodcache

